Feature/force update
KosukeSaigusa/mottai-flutter-app pull request #65
Opened 2023-07-23 13:22 UTC by narunblog

## Issue

#41 強制アップデート機能の実装

## 説明

強制アップデートのテストを追記しました。
テストを書く際にプロバイダーを追加した方がいいところがあったので、その部分も追加しました。

visibleForTestingに関しては不要と判断しました。
理由としては、今回記述したコードにプライベートにしたいが、テストで使うために公開しないといけない関数などがなかったからです。
今後そういった場面が訪れた際には記載したいと思います！

## UI
変更なし

## その他
なし

## チェックリスト

- [x] PR の冒頭に関連する Issue 番号を記載しましたか？
- [x] 本 PR の変更に関して、エディタや IDE で意図しない警告は増えていませんか？（lint 警告やタイポなど）
- [x] Issue の完了の定義は満たせていますか？

2023-07-24 03:38 UTC, KosukeSaigusa commented on packages/mottai_flutter_app/lib/force_update/force_update.dart
> +final isIOSProvider = Provider.autoDispose<bool>((_) => Platform.isIOS);
[感想（任意）]

iOS だけ Provider があるのは非対称な感じもしますが、iOS or Android でしか使用しないので、これでもいいかなとも思いました！

個人的には `Platform` 自体を提供する Provider 定義するのをはじはイメージしていました。

2023-07-24 04:06 UTC, KosukeSaigusa requested changes

2023-07-24 04:06 UTC, KosukeSaigusa commented on packages/mottai_flutter_app/test/force_update_test.dart
> +      // 値はtrueになること
false?

2023-07-24 04:06 UTC, KosukeSaigusa commented on packages/mottai_flutter_app/test/force_update_test.dart
> +    test('iosの時、iOSForceUpdateがfalseの場合かつバージョンが範囲外の時はtrue', () async {
[任意] 

ここから iOS の場合、Android の場合でテストが続くので、それぞれの group を作っても見やすいかも（それぞれの test の `description` が減らせる）のでいいかもなとも思いました！

2023-07-24 04:06 UTC, KosukeSaigusa commented on packages/mottai_flutter_app/test/force_update_test.dart
> +    test('androidの時、androidForceUpdateがfalseの場合かつバージョンが範囲外の時はtrue', () async {
[一応確認（仕様）]

上でも仕様の確認についてコメントを書いたのですが、

- forceUpdate: false
- 最低限必要なバージョンに達していない

の場合は「強制アップデートしない」で認識合っていそうですか？

2023-07-24 04:06 UTC, KosukeSaigusa commented on packages/mottai_flutter_app/test/force_update_test.dart
> +        appName: 'test_mottai_flutter_app_monorepo',
[軽微]

めちゃ細かいですしテストに関係ないですが、これは mottai_flutter_app パッケージにかかれているので monorepo の名前は出てこないかなと思いました！

2023-07-24 04:06 UTC, KosukeSaigusa commented on packages/mottai_flutter_app/test/force_update_test.dart
> +      // 値はtrueになること
false?

2023-07-25 17:04 UTC, narunblog commented on packages/mottai_flutter_app/lib/force_update/force_update.dart
> +final isIOSProvider = Provider.autoDispose<bool>((_) => Platform.isIOS);
PlatformProviderみたいなのが作成難しかったのでTargetPlatformを使ってOS分岐するようにしました。。。
TargetPlatformだとテスト時のオーバーライドもできるようでテスト含めるならこちらの方が推奨されてました！

でもPlatformProviderは作成したい。。。。

2023-07-25 17:06 UTC, narunblog commented on packages/mottai_flutter_app/lib/force_update/force_update.dart
> +              return true;
重複コード部分はisCurrentVersionLessThanMinimumメソッドとして切り出しました！
lib/package_info.dartに移動しています

ユニットテスト追加完了

2023-07-25 17:09 UTC, narunblog commented on packages/mottai_flutter_app/lib/force_update/force_update.dart
> +        return false;
これの書き方は以下のようであっていますでしょうか？
`if (currentVersionValue < minRequiredVersionValue) return false;`

フォーマットされてしまい、うまくいかないことがあります

2023-07-25 17:09 UTC, narunblog commented on packages/mottai_flutter_app/lib/force_update/force_update.dart
> +  return int.parse(sb.toString());
lib/package_info.dartに移動しました！
テスト追加完了

2023-07-25 17:10 UTC, narunblog commented on packages/mottai_flutter_app/lib/force_update/ui/force_update_controller.dart
ファイル削除

2023-07-25 17:10 UTC, narunblog commented on packages/mottai_flutter_app/lib/force_update/force_update.dart
> +final forceUpdateFutureProvider =
変数名修正

2023-07-25 17:10 UTC, narunblog commented on packages/mottai_flutter_app/lib/force_update/force_update.dart
> +final isForceUpdateProvider = StateProvider.autoDispose<bool>(
isForceUpdateRequiredに修正

2023-07-25 17:12 UTC, narunblog commented on packages/mottai_flutter_app/lib/force_update/ui/force_update.dart
> +                            await showDialog<Widget>(
エラーが発生してしまい、ダイアログの表示ができないため書き方の指導をして欲しいです。

例外が発生しました
FlutterError (Navigator operation requested with a context that does not include a Navigator.
The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.)

2023-07-25 17:12 UTC, narunblog commented on packages/mottai_flutter_app/test/force_update_test.dart
> +      // 値はtrueになること
falseでした！
修正済み

2023-07-25 17:14 UTC, narunblog commented on packages/mottai_flutter_app/test/force_update_test.dart
> +    test('iosの時、iOSForceUpdateがfalseの場合かつバージョンが範囲外の時はtrue', () async {
確かにそうだなと思いました！
iOSとandroidでgroup作成することでdescriptionをシンプルに
OSのオーバーライドもグループごとにsetUpを使うことで綺麗にまとまりました。

2023-07-25 17:17 UTC, narunblog commented on packages/mottai_flutter_app/test/force_update_test.dart
> +    test('androidの時、androidForceUpdateがfalseの場合かつバージョンが範囲外の時はtrue', () async {
- forceUpdate: false
- 最低限必要なバージョンに達していない

強制アップデートする認識でいました！

今は修正してforceUpdateは使わないようにしています。
仕様の確認を後日させてください

2023-07-25 17:17 UTC, narunblog commented on packages/mottai_flutter_app/test/force_update_test.dart
> +        appName: 'test_mottai_flutter_app_monorepo',
確かにそうでした！たぶんコピペする場所を間違えました！
修正しました！

2023-07-25 17:17 UTC, narunblog commented on packages/mottai_flutter_app/test/force_update_test.dart
> +      // 値はtrueになること
false!!

2023-07-26 04:34 UTC, KosukeSaigusa commented on packages/mottai_flutter_app/lib/force_update/force_update.dart
> +        return false;
@narunblog 

```dart
if (currentVersionValue < minRequiredVersionValue) {
  return false;
}
```

のように書ける気がします！

2023-07-26 04:39 UTC, KosukeSaigusa commented on packages/mottai_flutter_app/lib/force_update/ui/force_update.dart
> +                            await showDialog<Widget>(
@narunblog すみません、手元で試して私が用意しているコードに問題があるような気がしています🙏
よって、いまはこのままで大丈夫です！

2023-07-26 04:39 UTC, KosukeSaigusa commented on packages/mottai_flutter_app/test/force_update_test.dart
> +    test('androidの時、androidForceUpdateがfalseの場合かつバージョンが範囲外の時はtrue', () async {
@narunblog 

強制アップデートをする条件は「forceUpdate が true かつ、iOS/Android の自分が使用しているバージョンが、その minRequiredVersion に達していない」です！
「minRequiredVersion に達していなければ自動的に強制アップデートする」みたいな仕様にすることも考えられますが「minRequiredVersion はあるけどいまは強制アップデートしなくていいや」といったときに強制アップデートを引っ込めたくなる可能性もあるかもなと思い、そのように認識しています！
よって、forceUpdate は強制アップデートをしたい期間に手動で true にし、そうでない期間は false にしておくような認識でした！

2023-07-26 04:54 UTC, KosukeSaigusa commented on packages/mottai_flutter_app/lib/force_update/ui/force_update.dart
> +                            await showDialog<Widget>(
といいつつ、もう本件修正したので、main を取り込んだら動くと思います！🙏
こんな感じ：
https://github.com/KosukeSaigusa/mottai-flutter-app/blob/b9491c2d028e92f970a23a4135c6ffb7d391b340/packages/mottai_flutter_app/lib/development/sample_todo/ui/sample_todos_controller.dart#L35

2023-07-26 15:02 UTC, narunblog commented on packages/mottai_flutter_app/lib/force_update/force_update.dart
> +        return false;
ありがとうございます！

2023-07-26 15:34 UTC, KosukeSaigusa approved these changes

2023-07-26 15:54 UTC, merged