#36 create generic image widget
KosukeSaigusa/mottai-flutter-app pull request #69
Opened 2023-07-24 03:43 UTC by haterain0203

## Issue

close #36 

## 説明

- 汎用的な画像Widgetの作成
  - cached_network_image を使用
  - 円 or 正方形 or 長方形を指定できる（それ用のenumを作成）
  - サイズ（縦）を指定できる
  - サイズ（横）は、円・正方形の場合は、サイズ（縦）を適用し、長方形の場合はサイズ（縦）の2倍とした
  - 指定がない場合はデフォルト値として縦横 64とした
  - 角丸サイズを指定できる
  - 画像をタップした場合のVoidCallbackを指定できる
  - imageUrlが空文字の場合は代わりのグレー色プレイスホルダーっぽい見た目に
- 上記Widgetのサンプルを表示するdevelopment/development_components/develop/components.dartの追加
- development/development_items/development_items.dart内に上記サンプルページへの動線追加

## UI
### 開発ページ内に「Components」追加
<img src="https://github.com/KosukeSaigusa/mottai-flutter-app/assets/58384546/d3f0d7d8-ecf9-4659-82e6-bcb65bd0b5fb" width=300>

### 開発中のComponentsページ
<img src="https://github.com/KosukeSaigusa/mottai-flutter-app/assets/58384546/f95c13a5-199c-4cb6-80aa-515c0f237ff6" width=300>

## その他

レビューのほどよろしくお願いします！

## チェックリスト

- [x] PR の冒頭に関連する Issue 番号を記載しましたか？
- [x] 本 PR の変更に関して、エディタや IDE で意図しない警告は増えていませんか？（lint 警告やタイポなど）
- [x] Issue の完了の定義は満たせていますか？

2023-07-24 04:12 UTC, KosukeSaigusa commented on packages/dart_flutter_common/lib/src/components/image.dart
> +    // 指定がない場合は、defaultとして64.0が入る
このような説明は、`height` 自体の定義に doc comment（3 本スラッシュ `///` のコメント）として書くと、利用する側がエディタでカーソルを合わせることでその内容を確認できるのでやってみてください！

2023-07-24 04:36 UTC, KosukeSaigusa requested changes

2023-07-24 04:36 UTC, KosukeSaigusa commented on packages/dart_flutter_common/lib/src/components/image.dart
> +    return imageUrl.isEmpty
[任意（好みの問題）]

3 項演算子でなくていいなら、単に

```dart
if (condition) {
  return something;
}
return somethingElse;
```

が私は好きです！（インデントが減って見やすい、if 文の条件が増えても 3 項演算子がネストするようなことにならない）

2023-07-24 04:36 UTC, KosukeSaigusa commented on packages/dart_flutter_common/lib/src/components/image.dart
> +    // 指定がない場合は、defaultとして64.0が入る
このような説明は、`height` 自体の定義に doc comment（3 本スラッシュ `///` のコメント）として書くと、利用する側がエディタでカーソルを合わせることでその内容を確認できるのでやってみてください！

2023-07-24 04:36 UTC, KosukeSaigusa commented on packages/dart_flutter_common/lib/src/components/image.dart
> +              ),
[追加の提案] 

画像の読み込み中は `CircularProgressIndicator` のぐるぐるではなく、使用者が任意のウィジェットを渡したくなることもほぼ間違いなくあるので、任意で渡せるようにしましょうか！（また、そのときのデフォルトのウィジェットも `CircularProgressIndicator()` よりも、単にその形のグレー色のウィジェットのほうが良さそうな気がしています）

2023-07-24 04:36 UTC, KosukeSaigusa commented on packages/dart_flutter_common/lib/src/components/image.dart
> +    const defaultSize = 64.0;
このクラス自体の変数として

`static const double _defaultSize = 64;` みたいにしましょうか

2023-07-24 04:36 UTC, KosukeSaigusa commented on packages/dart_flutter_common/lib/src/components/image.dart
> +    this.radius,
この画像を使用する人が、画像 URL と形に加えて、

- 高さ
- 半径

を渡すというのがちょっとアンバランスな感じがしてどうなんだろうと思っています。

また、これ以下の実装の話ですが、長方形の場合は常に横幅は高さの 2 倍にする仕様になっていますか？（おそらく 1:2 は一般的画像のアスペクト比というわけでもないでしょうし、「汎用的な画像ウィジェット」としては、長方形の場合は、高さと幅を両方指定するようにするべきかな〜！と思っています！）

2023-07-24 04:36 UTC, KosukeSaigusa commented on packages/dart_flutter_common/lib/src/components/image.dart
> +  const GenericImageWidget({
下でも指摘した、「形ごとに渡すべきサイズに関する値の種類が異なる」という仕様の話にも関連して、これを名前付きコンストラクタにする（イニシャライザリストも活用する）のはどうでしょうか？

- https://dart.dev/language/constructors#named-constructors
- https://dart.dev/language/constructors#initializer-list

そうすると、それぞの名前付きコンストラクタごとに渡すパラメータを変えられるように思います（たとえば円と正方形では単に`size`、長方形では `width` と `height` のような感じ）。

```dart
GenericImageWidget.circle(/* 省略 */): imageShape = ImageShape.circle;

GenericImageWidget.square(/* 省略 */): imageShape = ImageShape.square;

GenericImageWidget.rectangle(/* 省略 */): imageShape = ImageShape.rectangle;
```

2023-07-24 04:36 UTC, KosukeSaigusa commented on packages/dart_flutter_common/lib/src/components/image.dart
> +    return Center(
ここもそのほうが見やすければ `ImageShape` で `switch-case` 書いてしまっていいとも思います。

2023-07-24 04:36 UTC, KosukeSaigusa commented on packages/dart_flutter_common/lib/src/components/image.dart
> +        : height ?? defaultSize;
上で指摘した通り、この仕様はやめることになると思います。

2023-07-24 04:36 UTC, KosukeSaigusa commented on packages/dart_flutter_common/lib/src/components/image.dart
> +          )
これは `Colors.grey` を直接渡すことで `_ImageDisplayContainer` 側でその見た目に合うようなウィジェットを表示するというよりは、ウィジェットを分けてしまう（`PlaceholderImage` みたいな）か名前付き引数（`_ImageDisplayContainer.placeholder(/* 省略 */)` みたいな）かで書くほうが読んですぐに理解できると思います！（現状だと、ここだけ読んでどんな見た目になりそうか想像できない。`PlaceholderImage` のように書いてあると「ああ、画像が空っぽのときのプレースホルダ画像なんだろうな」とすぐわかる）

2023-07-24 04:36 UTC, KosukeSaigusa commented on packages/mottai_flutter_app/lib/development/deveopment_components/development_components.dart
> +      body: Column(
[任意]

エラーのケース（もし可能なら、loading のケース）の見た目のサンプルもあると嬉しいです！

2023-07-24 04:45 UTC, KosukeSaigusa commented on packages/dart_flutter_common/lib/src/components/image.dart
> +    // 長方形が指定された場合のみ、指定されたheightの2倍の値またはdefaulSizeの2倍の値をwidthに設定する
[タイポ]

defaulSize → defaultSize

2023-07-24 12:50 UTC, haterain0203 commented on packages/dart_flutter_common/lib/src/components/image.dart
> +  const GenericImageWidget({
ありがとうございます！
恥ずかしながら名前付きコンストラクタを理解できていなかったので勉強になりました・・・！

[1e562cc](https://github.com/KosukeSaigusa/mottai-flutter-app/pull/69/commits/1e562ccbf34a39c304c169a26d186b0801cffde1)

上記のような対応でいかがでしょうか！？

2023-07-24 12:51 UTC, haterain0203 commented on packages/dart_flutter_common/lib/src/components/image.dart
> +    const defaultSize = 64.0;
ありがとうございます！

[f12a6b0](https://github.com/KosukeSaigusa/mottai-flutter-app/pull/69/commits/f12a6b0f50ff50d3202cea3d03dba881591ce20b)

にて対応しました

2023-07-24 12:52 UTC, haterain0203 commented on packages/dart_flutter_common/lib/src/components/image.dart
> +    return Center(
ありがとうございます！

[30e2a0c](https://github.com/KosukeSaigusa/mottai-flutter-app/pull/69/commits/30e2a0c0fdc8f935b8819a1c21bce86742ae32c6)

上記のように修正してみたのですが、どうでしょうか？

2023-07-24 12:53 UTC, haterain0203 commented on packages/dart_flutter_common/lib/src/components/image.dart
> +          )
なるほど、確かに変更前だと「ここだけ読んでどんな見た目になるか想像できない」ですね・・・

[fda64db](https://github.com/KosukeSaigusa/mottai-flutter-app/pull/69/commits/fda64dbdabc383d5c89f9abc1c9f01e8ebb7d9bc)

にて、.placeholderを作ってみました！

2023-07-24 12:54 UTC, haterain0203 commented on packages/dart_flutter_common/lib/src/components/image.dart
> +              ),
ありがとうございます！

[c03f552](https://github.com/KosukeSaigusa/mottai-flutter-app/pull/69/commits/c03f552b5aee18d60db3a1e2b1b86cfc5aed7627)

にて対応しました。

2023-07-24 12:54 UTC, haterain0203 commented on packages/dart_flutter_common/lib/src/components/image.dart
> +    return imageUrl.isEmpty
ありがとうございます！

[e3f09e5](https://github.com/KosukeSaigusa/mottai-flutter-app/pull/69/commits/e3f09e566876b14dd257eba0e41458f6d207e9b0)

にて対応しました！

2023-07-24 12:55 UTC, haterain0203 commented on packages/dart_flutter_common/lib/src/components/image.dart
> +    // 指定がない場合は、defaultとして64.0が入る
ありがとうございます！
今回は該当箇所が削除になりましたが、次回こういったシチュエーションがあった際は、doc commentにします！

2023-07-25 05:04 UTC, KosukeSaigusa commented on packages/dart_flutter_common/lib/src/components/image.dart
> +  final Widget? loading;
[軽微]

`loadingWidget` か `loadingPlaceholder` に変えましょうか！

2023-07-25 05:04 UTC, KosukeSaigusa commented on packages/dart_flutter_common/lib/src/components/image.dart
> +        {
この波括弧 `{}` は不要ではないですか？

2023-07-26 14:47 UTC, haterain0203 commented on packages/dart_flutter_common/lib/src/components/image.dart
> +  final Widget? loading;
ありがとうございます！

[d32565b](https://github.com/KosukeSaigusa/mottai-flutter-app/pull/69/commits/d32565b90d72909255fe49d9275eaf60951e78a3)
にて修正しました。

2023-07-26 14:47 UTC, haterain0203 commented on packages/dart_flutter_common/lib/src/components/image.dart
> +        {
ありがとうございます！
不要ですね・・・

[ec98a2b](https://github.com/KosukeSaigusa/mottai-flutter-app/pull/69/commits/ec98a2bb38237cd1784666b6945f0d8c691d7ff8)
にて修正しました

2023-07-26 14:50 UTC, haterain0203 commented on packages/mottai_flutter_app/lib/development/deveopment_components/development_components.dart
> +      body: Column(
[cee51c7](https://github.com/KosukeSaigusa/mottai-flutter-app/pull/69/commits/cee51c74d6a7f194ff91e5063b60021328791740)
にてエラーのケースのサンプルを追加しました！

[7167511](https://github.com/KosukeSaigusa/mottai-flutter-app/pull/69/commits/7167511383068d3a9653e2d33c61d3a7be3fb6ee)
で、エラーケースの場合は指定された形やサイズの中にアイコンを表示するようにしてみましたが、いかがでしょう？
（元々はアイコンのみ表示される仕様にしていた）

loading のケースは、GPT先生に相談して
http://deelay.me/
というサービスを教えてもらったんですが、今は動作してないようでした・・・
他に実現できる方法がわからなかったので、loadingのケースは対応できていません。

2023-07-26 15:21 UTC, KosukeSaigusa approved these changes

2023-07-27 00:04 UTC, merged